{
  "openapi": "3.0.0",
  "paths": {
    "/": {
      "get": {
        "operationId": "AppController_getHello",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "App"
        ]
      }
    },
    "/users": {
      "post": {
        "description": "Chỉ dành cho Admin",
        "operationId": "UsersController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateUserDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Tạo thành công"
          },
          "400": {
            "description": "Dữ liệu đầu vào không hợp lệ"
          },
          "403": {
            "description": "Không có quyền truy cập"
          }
        },
        "security": [
          {
            "JWT-auth": []
          }
        ],
        "summary": "Tạo tài khoản mới",
        "tags": [
          "Người dùng (Users)"
        ]
      },
      "get": {
        "operationId": "UsersController_findAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "security": [
          {
            "JWT-auth": []
          }
        ],
        "tags": [
          "Người dùng (Users)"
        ]
      }
    },
    "/users/{id}": {
      "get": {
        "operationId": "UsersController_findOne",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "security": [
          {
            "JWT-auth": []
          }
        ],
        "tags": [
          "Người dùng (Users)"
        ]
      },
      "patch": {
        "operationId": "UsersController_update",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateUserDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "security": [
          {
            "JWT-auth": []
          }
        ],
        "tags": [
          "Người dùng (Users)"
        ]
      },
      "delete": {
        "operationId": "UsersController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "security": [
          {
            "JWT-auth": []
          }
        ],
        "tags": [
          "Người dùng (Users)"
        ]
      }
    },
    "/whitelist-ip": {
      "post": {
        "operationId": "WhitelistIpController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateWhitelistIpDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "WhitelistIp"
        ]
      },
      "get": {
        "operationId": "WhitelistIpController_findAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "WhitelistIp"
        ]
      }
    },
    "/whitelist-ip/{id}": {
      "get": {
        "operationId": "WhitelistIpController_findOne",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "WhitelistIp"
        ]
      },
      "patch": {
        "operationId": "WhitelistIpController_update",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateWhitelistIpDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "WhitelistIp"
        ]
      },
      "delete": {
        "operationId": "WhitelistIpController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "WhitelistIp"
        ]
      }
    },
    "/roles": {
      "post": {
        "operationId": "RolesController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateRoleDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Roles"
        ]
      },
      "get": {
        "operationId": "RolesController_findAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Roles"
        ]
      }
    },
    "/roles/{id}": {
      "get": {
        "operationId": "RolesController_findOne",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Roles"
        ]
      },
      "patch": {
        "operationId": "RolesController_update",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateRoleDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Roles"
        ]
      },
      "delete": {
        "operationId": "RolesController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Roles"
        ]
      }
    },
    "/permissions": {
      "post": {
        "operationId": "PermissionsController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreatePermissionDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          }
        },
        "tags": [
          "Permissions"
        ]
      },
      "get": {
        "operationId": "PermissionsController_findAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Permissions"
        ]
      }
    },
    "/permissions/{id}": {
      "get": {
        "operationId": "PermissionsController_findOne",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Permissions"
        ]
      },
      "patch": {
        "operationId": "PermissionsController_update",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdatePermissionDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Permissions"
        ]
      },
      "delete": {
        "operationId": "PermissionsController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Permissions"
        ]
      }
    },
    "/auth": {
      "post": {
        "operationId": "AuthController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAuthDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ]
      },
      "get": {
        "operationId": "AuthController_findAll",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ]
      }
    },
    "/auth/{id}": {
      "get": {
        "operationId": "AuthController_findOne",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ]
      },
      "patch": {
        "operationId": "AuthController_update",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateAuthDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ]
      },
      "delete": {
        "operationId": "AuthController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "string"
                }
              }
            }
          }
        },
        "tags": [
          "Auth"
        ]
      }
    },
    "/attribute": {
      "post": {
        "description": "Chỉ dành cho tài khoản có quyền Admin. Dùng để định nghĩa các thuộc tính mở rộng cho phân quyền.",
        "operationId": "AttributeController_create",
        "parameters": [],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateAttributeDto"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "data": {
                      "$ref": "#/components/schemas/ResponseAttributeDto"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 400,
                      "message": "Bad Request",
                      "requestId": "5ca179ab-b18f-44af-a565-bc7f1836c768",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 404,
                      "message": "Not Found",
                      "requestId": "80d59b47-0152-49e3-91e6-e088df64bf17",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 409,
                      "message": "Conflict",
                      "requestId": "393ff9e1-cae6-427f-9070-271bc55de7f4",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 500,
                      "message": "Internal Server Error",
                      "requestId": "358945e1-885e-48f3-8901-2914ac6bb4fd",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ],
        "summary": "Tạo điều kiện quyền mới",
        "tags": [
          "Attribute (Quản lý thuộc tính/điều kiện)"
        ]
      },
      "get": {
        "description": "Hỗ trợ lọc theo tên, sắp xếp và phân trang.",
        "operationId": "AttributeController_findAllPaginated",
        "parameters": [
          {
            "name": "search",
            "required": false,
            "in": "query",
            "description": "Tìm kiếm theo tên hoặc mô tả của điều kiện.",
            "schema": {
              "example": "department",
              "type": "string"
            }
          },
          {
            "name": "page",
            "required": false,
            "in": "query",
            "description": "Số trang hiện tại.",
            "schema": {
              "minimum": 1,
              "example": 1,
              "type": "number"
            }
          },
          {
            "name": "limit",
            "required": false,
            "in": "query",
            "description": "Số lượng bản ghi trên mỗi trang.",
            "schema": {
              "minimum": 1,
              "example": 10,
              "type": "number"
            }
          },
          {
            "name": "sortBy",
            "required": false,
            "in": "query",
            "description": "Trường dữ liệu dùng để sắp xếp.",
            "schema": {
              "example": "name",
              "type": "string"
            }
          },
          {
            "name": "sortOrder",
            "required": false,
            "in": "query",
            "description": "Thứ tự sắp xếp.",
            "schema": {
              "default": "asc",
              "example": "asc",
              "type": "string",
              "enum": [
                "asc",
                "desc"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "items": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/ResponseAttributeDto"
                          }
                        },
                        "meta": {
                          "type": "object",
                          "properties": {
                            "total": {
                              "type": "number"
                            },
                            "page": {
                              "type": "number"
                            },
                            "limit": {
                              "type": "number"
                            },
                            "totalPages": {
                              "type": "number"
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 400,
                      "message": "Bad Request",
                      "requestId": "5ca179ab-b18f-44af-a565-bc7f1836c768",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 404,
                      "message": "Not Found",
                      "requestId": "80d59b47-0152-49e3-91e6-e088df64bf17",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 409,
                      "message": "Conflict",
                      "requestId": "393ff9e1-cae6-427f-9070-271bc55de7f4",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 500,
                      "message": "Internal Server Error",
                      "requestId": "358945e1-885e-48f3-8901-2914ac6bb4fd",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ],
        "summary": "Lấy danh sách điều kiện quyền (phân trang)",
        "tags": [
          "Attribute (Quản lý thuộc tính/điều kiện)"
        ]
      }
    },
    "/attribute/{id}": {
      "get": {
        "operationId": "AttributeController_findOne",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "ID của điều kiện quyền (định dạng UUID)",
            "schema": {
              "format": "uuid",
              "example": "550e8400-e29b-41d4-a716-446655440000",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "data": {
                      "$ref": "#/components/schemas/ResponseAttributeDto"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 400,
                      "message": "Bad Request",
                      "requestId": "5ca179ab-b18f-44af-a565-bc7f1836c768",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 404,
                      "message": "Not Found",
                      "requestId": "80d59b47-0152-49e3-91e6-e088df64bf17",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 409,
                      "message": "Conflict",
                      "requestId": "393ff9e1-cae6-427f-9070-271bc55de7f4",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 500,
                      "message": "Internal Server Error",
                      "requestId": "358945e1-885e-48f3-8901-2914ac6bb4fd",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ],
        "summary": "Lấy chi tiết một điều kiện quyền",
        "tags": [
          "Attribute (Quản lý thuộc tính/điều kiện)"
        ]
      },
      "patch": {
        "operationId": "AttributeController_update",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "ID của điều kiện quyền (định dạng UUID)",
            "schema": {
              "format": "uuid",
              "example": "550e8400-e29b-41d4-a716-446655440000",
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateAttributeDto"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "data": {
                      "$ref": "#/components/schemas/ResponseAttributeDto"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 400,
                      "message": "Bad Request",
                      "requestId": "5ca179ab-b18f-44af-a565-bc7f1836c768",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 404,
                      "message": "Not Found",
                      "requestId": "80d59b47-0152-49e3-91e6-e088df64bf17",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 409,
                      "message": "Conflict",
                      "requestId": "393ff9e1-cae6-427f-9070-271bc55de7f4",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 500,
                      "message": "Internal Server Error",
                      "requestId": "358945e1-885e-48f3-8901-2914ac6bb4fd",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ],
        "summary": "Cập nhật điều kiện quyền",
        "tags": [
          "Attribute (Quản lý thuộc tính/điều kiện)"
        ]
      },
      "delete": {
        "operationId": "AttributeController_remove",
        "parameters": [
          {
            "name": "id",
            "required": true,
            "in": "path",
            "description": "ID của điều kiện quyền (định dạng UUID)",
            "schema": {
              "format": "uuid",
              "example": "550e8400-e29b-41d4-a716-446655440000",
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "properties": {
                    "success": {
                      "type": "boolean",
                      "default": true
                    },
                    "data": {
                      "$ref": "#/components/schemas/ResponseAttributeDto"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 400,
                      "message": "Bad Request",
                      "requestId": "5ca179ab-b18f-44af-a565-bc7f1836c768",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 404,
                      "message": "Not Found",
                      "requestId": "80d59b47-0152-49e3-91e6-e088df64bf17",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 409,
                      "message": "Conflict",
                      "requestId": "393ff9e1-cae6-427f-9070-271bc55de7f4",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/ErrorResponseDto"
                    }
                  ],
                  "example": {
                    "success": false,
                    "error": {
                      "statusCode": 500,
                      "message": "Internal Server Error",
                      "requestId": "358945e1-885e-48f3-8901-2914ac6bb4fd",
                      "timestamp": "2026-05-01T09:12:17.327Z",
                      "path": "/attribute"
                    }
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearer": []
          }
        ],
        "summary": "Xóa điều kiện quyền",
        "tags": [
          "Attribute (Quản lý thuộc tính/điều kiện)"
        ]
      }
    }
  },
  "info": {
    "title": "NestJS Pro API",
    "description": "Tài liệu API chi tiết cho dự án",
    "version": "1.0",
    "contact": {}
  },
  "tags": [],
  "servers": [
    {
      "url": "http://localhost:3000/",
      "description": "Local environment"
    },
    {
      "url": "https://yourdomain.com",
      "description": "Staging"
    }
  ],
  "components": {
    "securitySchemes": {
      "JWT-auth": {
        "scheme": "bearer",
        "bearerFormat": "JWT",
        "type": "http",
        "name": "JWT",
        "description": "Nhập mã token vào đây",
        "in": "header"
      }
    },
    "schemas": {
      "CreateUserDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "@description Họ và tên đầy đủ",
            "example": "Nguyễn Văn A",
            "maxLength": 50
          },
          "username": {
            "type": "string",
            "description": "Tên đăng nhập (chỉ chứa chữ, số và _)",
            "example": "admin_pro",
            "minLength": 5,
            "pattern": "^[a-zA-Z0-9_]+$"
          },
          "password": {
            "type": "string",
            "description": "Mật khẩu (ít nhất 1 hoa, 1 thường, 1 số)",
            "example": "Password@123",
            "minLength": 8
          }
        },
        "required": [
          "name",
          "username",
          "password"
        ]
      },
      "UpdateUserDto": {
        "type": "object",
        "properties": {}
      },
      "CreateWhitelistIpDto": {
        "type": "object",
        "properties": {}
      },
      "UpdateWhitelistIpDto": {
        "type": "object",
        "properties": {}
      },
      "CreateRoleDto": {
        "type": "object",
        "properties": {}
      },
      "UpdateRoleDto": {
        "type": "object",
        "properties": {}
      },
      "PermissionConditionDto": {
        "type": "object",
        "properties": {
          "attribute_id": {
            "type": "string",
            "format": "uuid"
          },
          "logic": {
            "type": "object"
          }
        },
        "required": [
          "attribute_id",
          "logic"
        ]
      },
      "CreatePermissionDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          },
          "conditions": {
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/PermissionConditionDto"
            }
          }
        },
        "required": [
          "name",
          "conditions"
        ]
      },
      "UpdatePermissionDto": {
        "type": "object",
        "properties": {}
      },
      "CreateAuthDto": {
        "type": "object",
        "properties": {}
      },
      "UpdateAuthDto": {
        "type": "object",
        "properties": {}
      },
      "ErrorDetailDto": {
        "type": "object",
        "properties": {
          "statusCode": {
            "type": "number",
            "example": 409
          },
          "message": {
            "type": "object",
            "example": "attribute với name này đã tồn tại."
          },
          "requestId": {
            "type": "string",
            "example": "b4455dc9-313b-4914-8fe2-9e257abe29b8"
          },
          "timestamp": {
            "type": "string",
            "example": "2026-04-30T11:46:33.862Z"
          },
          "path": {
            "type": "string",
            "example": "/attribute"
          }
        },
        "required": [
          "statusCode",
          "message",
          "requestId",
          "timestamp",
          "path"
        ]
      },
      "ErrorResponseDto": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean",
            "example": false
          },
          "error": {
            "$ref": "#/components/schemas/ErrorDetailDto"
          }
        },
        "required": [
          "success",
          "error"
        ]
      },
      "ResponseAttributeDto": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "example": "123"
          },
          "name": {
            "type": "string"
          },
          "_count": {
            "type": "object",
            "properties": {
              "conditions": {
                "type": "number"
              }
            },
            "required": [
              "conditions"
            ]
          }
        },
        "required": [
          "id",
          "name"
        ]
      },
      "CreateAttributeDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "@description Tên định danh duy nhất của thuộc tính (slug).",
            "example": "department_code",
            "maxLength": 255
          }
        },
        "required": [
          "name"
        ]
      },
      "UpdateAttributeDto": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string",
            "description": "@description Tên định danh duy nhất của thuộc tính (slug).",
            "example": "department_code",
            "maxLength": 255
          }
        }
      }
    }
  }
}